name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PROJECT_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 13.59.140.98 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ec2-user@13.59.140.98 << 'EOF'
          cd ~/node-pm2-docker-app
          git pull origin main
          docker build -t pm2-image .
          docker stop pm2-container || true
          docker rm pm2-container || true
          docker run -d --name pm2-container --network monitoring -p 3010:3000 pm2-image
          EOF
