name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_PROJECT_KEY }}

      - name: Deploy using SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/node-pm2-docker-app || git clone https://github.com/JesonNehru/node-pm2-docker-app.git ~/node-pm2-docker-app && cd ~/node-pm2-docker-app

            git pull origin main
            docker build -t pm2-image .
            docker rm -f pm2-container || true
            docker run -d \
              --name pm2-container \
              --network monitoring \
              -p 3010:3000 \
              pm2-image
          EOF
