name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:  # ✅ This must be indented under jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_PROJECT_KEY }}

      - name: Test SSH connection
        run: |
          echo "👉 Trying SSH connection to ${{ secrets.EC2_HOST }}"
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "echo ✅ SSH success"
