name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  HEAD
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy app to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} << 'EOF'
          cd ~/node-pm2-docker-app || git clone https://github.com/JesonNehru/node-pm2-docker-app.git && cd node-pm2-docker-app
          git pull
          docker build -t node-pm2-app .
          docker rm -f $(docker ps -q --filter ancestor=node-pm2-app) || true
          docker run -d -p 3000:3000 node-pm2-app
        EOF

  deploy:  # ✅ This must be indented under jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_PROJECT_KEY }}

      - name: Test SSH connection
        run: |
          echo "👉 Trying SSH connection to ${{ secrets.EC2_HOST }}"
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "echo ✅ SSH success"
 59d9f2f1fbebb4c817c45f478cfd4e7f7403c423
